### ISSUE TITLE
Error using replace_errors with a validator with var_group

### ISSUE THREAD

**Issue by smartie5** [data-cleaning/errorlocate#19]
Using the var_group functionality in validator in combination with replace_errors results in the error message:
"Error: invalid assignment for reference class field ‘._miprules’, should be from class “list” or a subclass (was class “NULL”)
In addition: Warning message:
In to_miprules(rules) : Ignoring rules: V1"

I am using errorlocate version 0.2.0.

```ruby 
library(errorlocate)
library(validate)

df <- data.frame(a=-1, b=0)
rules <- validator(var_group(a,b)>=0)
replace_errors(df, rules)
```

**Comment by markvanderloo** [comment]
Thanks for the report! That's a bug.

**Comment by edwindj** [comment]
Looking into the issue: solvable, currently fails because it does not recognize the rule as a linear rule and therefore excludes it. 

- not confined to `errorlocate`: `validate` also has an issue with it: `rules$linear()` is  `FALSE`
- I think a useful method to add to a validator object would be an `$expand()` method that would return a new validator object in which all var_groups are expanded (so a $exprs).

**Comment by edwindj** [comment]
I fixed the current issue, however: assignments are not yet supported (will create new issue)
Thus:

```r
library(errorlocate)
library(validate)

df <- data.frame(a=-1, b=0)
# working
rules <- validator(var_group(a,b)>=0)
replace_errors(df, rules)

# not working
rules_assign <- validator(G := var_group(a,b), G >= 0)
replace_errors(df, rules_assign
```
