### ISSUE TITLE
Bug in locate_errors

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/errorlocate#31]
The following gives an invalid solution (version 0.5.1)

```r
library(errorlocate)
d <- data.frame(
  x = 10, y = NA, z=5
)
v <- validator(x + y == z, x>=0, y>=0)

out <- locate_errors(d,v)
out$errors

replace_errors(d,v)
```

**Comment by edwindj** [comment]
Bug is fixed, actually were multiple bugs rolled into one master bug:

*  when a variable had a missing value the mip problem was not well formulated (most of the times it worked in some cases it didn't). Should be fixed now

* as an optimization records without fails (as in `validate::confront` and `aggregate(cf, by="record"))` were skipped in `errorlocate`. This resulted in skipping the record above in the example: because `y == NA` `validate::confront` returns `NA` and not `fail`.
* This has been changed into that `errorlocate` now only skips records when there are no nNA or fails on a record.
